### ISSUE TITLE
To use with reqwest crate

### ISSUE THREAD

**Issue by vangork** [XOR-op/ja-tools#2]
reqwest v0.12.4 denpends on  rustls = "0.22.2"
current lastest reqwest v0.12.5 denpends on  rustls = "0.23.5"

Can you help build a new version to let reqwest use it? Thanks.

**Comment by vangork** [comment]
@XOR-op

**Comment by XOR-op** [comment]
@vangork I have updated the rustls dependency. Can you try `rustls = { git = "https://github.com/XOR-op/rustls.delta.git", branch = "v0.23.12" }` to see if it works?

**Comment by vangork** [comment]
Sure. Thanks!

**Comment by vangork** [comment]
It works perfectly!
